# Generated by Django 3.2.4 on 2021-06-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ad_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='status',
            field=models.BooleanField(choices=[('active', 'active'), ('inactive', 'inactive')], default=False),
        ),
        migrations.AlterField(
            model_name='slider',
            name='rank',
            field=models.ImageField(upload_to=''),
        ),
    ]
