# Generated by Django 3.2.4 on 2021-06-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210630_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='status',
            field=models.BooleanField(choices=[('active', 'active'), ('inactive', 'inactive')], default=True),
        ),
    ]
