# Generated by Django 3.2.4 on 2021-06-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_slider_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default=False, max_length=500),
        ),
    ]
